### ISSUE TITLE
bad :buildcache tag for extras images

### ISSUE THREAD

**Issue by segyges** [coreweave/ml-containers#59]
Haven't checked any of the other  images, but [here](https://github.com/coreweave/ml-containers/pkgs/container/ml-containers%2Ftorch-extras) if you actually try to pull the "buildcache" tag it errors. That tag should really either be either available, or not listed in the repo. Normally I fix my versions but I'm just trying to pull something with a good pytorch install to run a terminal session; I understand the reasons to not use :latest or anything equivalent but in that case it really shouldn't be listed.

**Comment by dmarx** [comment]
It's an intermediate build artifact, i.e. an incomplete build. You're right, it's confusing and I've been annoyed as well when I tried to pull what I thought was equivalent to `latest` and it borked. I'm looking into what we can do to either clarify that this isn't meant to be used or better yet not have it visible.

**Comment by dmarx** [comment]
Future forward, buildcache images will not be publicly visible. Thanks for bringing this to our attention and helping us mitigate this source of confusion.
